### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by Dinistro** [circt-hls/circt-hls#7]
While setting up this project locally I found some minor things that break the build.

First of all, there are imports of `circt-hls/Dialect/Cosim/CosimEnums.(h|cpp).inc"` which is not generated by TableGen. I'm assuming that there are no enums in `Cosim` and thus no such files are generated.

Secondly, `lib/Transforms/CMakeLists.txt` references a `CleanUnregisteredAttrs.cpp` which does not exist. Removing this resolves the compilation error, but results in a linker error. The pass `CleanUnregisteredAttrs` pass is declared in `include/circt-hls/Transforms/Passes.td`, but there is no definition of the "constructor" function -> Linker error. 
Was this file just not commited or is this a leftover?

**Comment by Dinistro** [comment]
Looking at the last commit (https://github.com/circt-hls/circt-hls/commit/830b29c0312bdb0eee494493a50fa2377559458c) indicates that 
1. the generation of the enums was removed, but the includes remain. 
2. The pass was added, but the implementation file was missed.

**Comment by mortbopet** [comment]
Forgot to push a bunch of minor fixes which i had locally; syncing the repo should fixe some of the issue(s)...

**Comment by Dinistro** [comment]
The enum imports are still there, but I can provide a fix for that. Note that old files generated with tablegen remain in the build directory even when the generation was removed. This is probably the reason why this still builds on your machine.
